import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import { useEffect, useState } from 'react';
import Navbar from '@/components/Navbar';
import Schedule from '@/components/Schedule';
import Hero from '@/components/Hero';
import Title from '@/components/Title';
import Footer from '@/components/Footer';
import { littlestGuy } from '@/lib/Images';

export default function Home() {
	return (
		<>
			<Head>
				<title>PickHacks 2024</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={`${styles.main}`}>
				<Hero />
				<div className={styles.section} id='schedule'>
					<Title>Schedule</Title>
					<Schedule />
				</div>
				<div className={styles.section} id='schedule'>
					<Title>Prizes</Title>
					<p className={styles.fillerText}>Coming soon...</p>
				</div>
				<div className={styles.smallGuySection}>
					<img src={littlestGuy.src} />
				</div>
			</main>
			<Footer />
		</>
	);
}
