import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react';
import scheduleStyles from '../styles/Schedule.module.css'

const inter = Inter({ subsets: ['latin'] })

interface Event {
  day: string;
  event: string;
  time: string;
  location: string;
}

const data: Event[] = [
  {
      day: 'Friday',
      event: 'Breakfast',
      time: '9:00am',
      location: 'Mezzanine'
  },
  {
      day: 'Friday',
      event: 'Company Talk',
      time: '11:00am',
      location: 'Room 101'
  },
  {
      day: 'Friday',
      event: 'Lunch',
      time: '12:00am',
      location: 'Mezzanine'
  },
  {
      day: 'Friday',
      event: 'Escape Room Activity',
      time: '5:00pm',
      location: 'Room 213'
  },
  {
      day: 'Friday',
      event: 'Dinner',
      time: '7:00am',
      location: 'Mezzanine'
  },
  {
      day: 'Saturday',
      event: 'Breakfast',
      time: '7:00am - 8:00am',
      location: 'Upstairs'
  },
  {
      day: 'Sunday',
      event: 'Breakfast',
      time: '7:00am - 8:00am',
      location: 'Upstairs'
  }
];

function Schedule() {
  const [selected, setSelected] = useState<string>("Friday");
  const [currData, setCurrData] = useState<Event[]>([]);

  useEffect(() => {
      setCurrData([...data.filter((obj) => obj.day === selected)]);
  }, []);

  const toggle = (day: string) => {
      if (selected != day) {
          setSelected(day);
          setCurrData([...data.filter((obj) => obj.day === day)]);
      }
  };

  return (
      <div className={scheduleStyles.App}>
          <p className={scheduleStyles.title}>Schedule</p>
          <div className={scheduleStyles.row}>
              {['Friday', 'Saturday', 'Sunday'].map((day) => (
                  <p
                      key={day}
                      className={scheduleStyles.subtitle}
                      style={{ background: selected == day ? 'rgb(91, 82, 224)' : 'rgb(42, 20, 73)' }}
                      onClick={() => toggle(day)}
                  >
                      {day}
                  </p>
              ))}
          </div>
          {currData.map((obj) => (
              <div key={`${obj.day}-${obj.event}`} className={scheduleStyles.eventContainer}>
                  <div className={scheduleStyles.column}>
                      <p className={scheduleStyles.event}>{obj.event}</p>
                      <p className={scheduleStyles.time}>{obj.time}</p>
                  </div>
                  <div className={scheduleStyles.column}>
                      <p className={scheduleStyles.day}>{obj.location}</p>
                  </div>
              </div>
          ))}
      </div>
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>PickHacks 2024</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {Schedule()}
      </main>
    </>
  )
}
